version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/simple-app
hooks:
  ApplicationStop:
    - location: codedeploy/application_stop.sh
      runas: ubuntu
  BeforeInstall:
    - location: codedeploy/before_install.sh
      runas: root
      # Allow plenty of time to compile all the things.
      timeout: 6800
  ApplicationStart:
    - location: codedeploy/application_start.sh
      runas: root
    - location: codedeploy/bundle_install.sh
      runas: ubuntu
      # https://xkcd.com/303/
      timeout: 3000
  ValidateService:
    - location: codedeploy/validate_service.sh
      runas: ubuntu
